# -*- coding: utf-8 -*-
"""Hello World

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18PvTJ-dxtbkSJ6KlPRuObBr80_aTxARL
"""

# Displaying "Hello World!" on the screen 
# print is a Python defined default function, we are simply using it here
print("Hello World!")